/*
 *  BozoListDialog.java
 *
 *  gGo
 *  Copyright (C) 2002  Peter Strempel <pstrempel@t-online.de>
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
package ggo.igs.gui;

import ggo.igs.BozoHandler;
import ggo.gGo;
import ggo.utils.Settings;
import javax.swing.*;
import java.awt.event.*;
import java.util.ResourceBundle;

/**
 *  Dialog to manage the friends and bozos list.
 *
 * @author  Peter Strempel
 * @version $Revision: 1.3 $, $Date: 2002/09/21 12:39:56 $
 */
public class BozoListDialog extends javax.swing.JDialog {
    private BozoHandler bozoHandler;
    private KeyHandler keyHandler;
    private ResourceBundle igs_bozo_resources;

    /** Creates new form BozoListDialog */
    public BozoListDialog(java.awt.Frame parent, boolean modal, BozoHandler bozoHandler) {
        super(parent, modal);
        this.bozoHandler = bozoHandler;
        keyHandler = new KeyHandler();
        igs_bozo_resources = gGo.getIGSBozoResources();
        initComponents();
        messageCheckBox.setSelected(gGo.getSettings().doAutoReply());
        String s = gGo.getSettings().getAutoReply();
        if (s == null || s.length() == 0)
            s = igs_bozo_resources.getString("default_message");
        messageTextField.setText(s);
        messageTextField.setEnabled(messageCheckBox.isSelected());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        javax.swing.JPanel friendsPanel;
        javax.swing.JPanel msgPanel;
        javax.swing.JScrollPane friendsScrollPane;
        javax.swing.JButton addBozoButton;
        javax.swing.JPanel bozosPanel;
        javax.swing.JButton removeBozoButton;
        javax.swing.JPanel friendsAddRemovePanel;
        javax.swing.JPanel mainPanel;
        javax.swing.JPanel listsPanel;
        javax.swing.JScrollPane bozosScrollPane;
        javax.swing.JButton addFriendButton;
        javax.swing.JButton removeFriendButton;
        javax.swing.JPanel buttonPanel;
        javax.swing.JPanel bozosAddRemovePanel;
        javax.swing.JButton closeButton;

        mainPanel = new javax.swing.JPanel();
        listsPanel = new javax.swing.JPanel();
        friendsPanel = new javax.swing.JPanel();
        friendsScrollPane = new javax.swing.JScrollPane();
        friendsList = new javax.swing.JList();
        friendsAddRemovePanel = new javax.swing.JPanel();
        addFriendButton = new javax.swing.JButton();
        removeFriendButton = new javax.swing.JButton();
        bozosPanel = new javax.swing.JPanel();
        bozosScrollPane = new javax.swing.JScrollPane();
        bozosList = new javax.swing.JList();
        bozosAddRemovePanel = new javax.swing.JPanel();
        addBozoButton = new javax.swing.JButton();
        removeBozoButton = new javax.swing.JButton();
        msgPanel = new javax.swing.JPanel();
        messageCheckBox = new javax.swing.JCheckBox();
        messageTextField = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setTitle(igs_bozo_resources.getString("User_management"));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        mainPanel.setLayout(new java.awt.BorderLayout());

        mainPanel.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        listsPanel.setLayout(new javax.swing.BoxLayout(listsPanel, javax.swing.BoxLayout.X_AXIS));

        listsPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 0, 5)));
        friendsPanel.setLayout(new java.awt.BorderLayout());

        friendsPanel.setBorder(new javax.swing.border.TitledBorder(igs_bozo_resources.getString("Friends")));
        friendsScrollPane.setPreferredSize(new java.awt.Dimension(100, 200));
        friendsList.setModel(getFriendsModel());
        friendsList.addKeyListener(keyHandler);
        friendsScrollPane.setViewportView(friendsList);

        friendsPanel.add(friendsScrollPane, java.awt.BorderLayout.CENTER);

        friendsAddRemovePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        addFriendButton.setText(igs_bozo_resources.getString("Add"));
        addFriendButton.setToolTipText(igs_bozo_resources.getString("add_friend_tooltip"));
        addFriendButton.addKeyListener(keyHandler);
        addFriendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFriendButtonActionPerformed(evt);
            }
        });

        friendsAddRemovePanel.add(addFriendButton);

        removeFriendButton.setText(igs_bozo_resources.getString("Remove"));
        removeFriendButton.setToolTipText(igs_bozo_resources.getString("remove_friend_tooltip"));
        removeFriendButton.addKeyListener(keyHandler);
        removeFriendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFriendButtonActionPerformed(evt);
            }
        });

        friendsAddRemovePanel.add(removeFriendButton);

        friendsPanel.add(friendsAddRemovePanel, java.awt.BorderLayout.SOUTH);

        listsPanel.add(friendsPanel);

        bozosPanel.setLayout(new java.awt.BorderLayout());

        bozosPanel.setBorder(new javax.swing.border.TitledBorder(igs_bozo_resources.getString("Ignore")));
        bozosScrollPane.setPreferredSize(new java.awt.Dimension(100, 200));
        bozosList.setModel(getBozosModel());
        bozosList.addKeyListener(keyHandler);
        bozosScrollPane.setViewportView(bozosList);

        bozosPanel.add(bozosScrollPane, java.awt.BorderLayout.CENTER);

        bozosAddRemovePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        addBozoButton.setText(igs_bozo_resources.getString("Add"));
        addBozoButton.setToolTipText(igs_bozo_resources.getString("add_ignore_tooltip"));
        addBozoButton.addKeyListener(keyHandler);
        addBozoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBozoButtonActionPerformed(evt);
            }
        });

        bozosAddRemovePanel.add(addBozoButton);

        removeBozoButton.setText(igs_bozo_resources.getString("Remove"));
        removeBozoButton.setToolTipText(igs_bozo_resources.getString("remove_ignore_tooltip"));
        removeBozoButton.addKeyListener(keyHandler);
        removeBozoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBozoButtonActionPerformed(evt);
            }
        });

        bozosAddRemovePanel.add(removeBozoButton);

        bozosPanel.add(bozosAddRemovePanel, java.awt.BorderLayout.SOUTH);

        listsPanel.add(bozosPanel);

        mainPanel.add(listsPanel, java.awt.BorderLayout.CENTER);

        msgPanel.setLayout(new java.awt.BorderLayout());

        msgPanel.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)), new javax.swing.border.TitledBorder(igs_bozo_resources.getString("autoreply_message"))));
        messageCheckBox.setText(igs_bozo_resources.getString("Enable"));
        messageCheckBox.setToolTipText(igs_bozo_resources.getString("enable_tooltip"));
        messageCheckBox.addKeyListener(keyHandler);
        messageCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                messageCheckBoxItemStateChanged(evt);
            }
        });

        msgPanel.add(messageCheckBox, java.awt.BorderLayout.WEST);

        messageTextField.setText(igs_bozo_resources.getString("default_message"));
        messageTextField.setToolTipText(igs_bozo_resources.getString("default_message_tooltip"));
        messageTextField.addKeyListener(keyHandler);
        msgPanel.add(messageTextField, java.awt.BorderLayout.CENTER);

        mainPanel.add(msgPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        closeButton.setText(igs_bozo_resources.getString("Close"));
        closeButton.setToolTipText(igs_bozo_resources.getString("close_tooltip"));
        getRootPane().setDefaultButton(closeButton);
        closeButton.addKeyListener(keyHandler);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(closeButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }//GEN-END:initComponents

    private void messageCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_messageCheckBoxItemStateChanged
        messageTextField.setEnabled(messageCheckBox.isSelected());
    }//GEN-LAST:event_messageCheckBoxItemStateChanged

    private void addBozoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBozoButtonActionPerformed
        String s = JOptionPane.showInputDialog(this, igs_bozo_resources.getString("Enter_name:"));
        if (s != null && s.length() > 0) {
            bozoHandler.setBozoStatus(s, BozoHandler.PLAYER_STATUS_BOZO);
            updateLists();
        }
    }//GEN-LAST:event_addBozoButtonActionPerformed

    private void removeBozoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBozoButtonActionPerformed
        Object o[] = bozosList.getSelectedValues();
        for (int i=0, sz=o.length; i<sz; i++)
            bozoHandler.setBozoStatus((String)o[i], BozoHandler.PLAYER_STATUS_NEUTRAL);
        updateLists();
    }//GEN-LAST:event_removeBozoButtonActionPerformed

    private void addFriendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFriendButtonActionPerformed
        String s = JOptionPane.showInputDialog(this, igs_bozo_resources.getString("Enter_name:"));
        if (s != null && s.length() > 0) {
            bozoHandler.setBozoStatus(s, BozoHandler.PLAYER_STATUS_FRIEND);
            updateLists();
        }
    }//GEN-LAST:event_addFriendButtonActionPerformed

     private void removeFriendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFriendButtonActionPerformed
        Object o[] = friendsList.getSelectedValues();
        for (int i=0, sz=o.length; i<sz; i++)
            bozoHandler.setBozoStatus((String)o[i], BozoHandler.PLAYER_STATUS_NEUTRAL);
        updateLists();
    }//GEN-LAST:event_removeFriendButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        closeDialog(null);
    }//GEN-LAST:event_closeButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        gGo.getSettings().setDoAutoReply(messageCheckBox.isSelected());
        String s = messageTextField.getText();
        if (s == null || s.length() == 0) {
            s = igs_bozo_resources.getString("default_message");
            messageTextField.setText(s);
        }
        gGo.getSettings().setAutoReply(s);
        gGo.getSettings().saveSettings();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    void updateLists() {
        friendsList.setModel(getFriendsModel());
        bozosList.setModel(getBozosModel());
    }

    private DefaultComboBoxModel getFriendsModel() {
        return new DefaultComboBoxModel(bozoHandler.getFriends());
    }

    private DefaultComboBoxModel getBozosModel() {
        return new DefaultComboBoxModel(bozoHandler.getBozos());
    }

    /*
    public static void main(String args[]) {
        new BozoListDialog(new javax.swing.JFrame(), false, new BozoHandler()).show();
    }
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList bozosList;
    private javax.swing.JCheckBox messageCheckBox;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JList friendsList;
    // End of variables declaration//GEN-END:variables

    class KeyHandler extends KeyAdapter {
        public void keyPressed(KeyEvent e) {
            if (e.getKeyCode() == KeyEvent.VK_ESCAPE)
                closeDialog(null);
        }
    }
}
